package vn.id.tozydev.lucidabyss.styles

import com.varabyte.kobweb.compose.css.StyleVariable
import com.varabyte.kobweb.compose.ui.Modifier
import com.varabyte.kobweb.compose.ui.graphics.Color
import com.varabyte.kobweb.compose.ui.modifiers.*
import com.varabyte.kobweb.silk.init.InitSilk
import com.varabyte.kobweb.silk.init.InitSilkContext
import com.varabyte.kobweb.silk.init.registerStyleBase
import org.jetbrains.compose.web.css.*

object ColorScheme {
    val Primary by StyleVariable<CSSColorValue>()
    val OnPrimary by StyleVariable<CSSColorValue>()
    val PrimaryContainer by StyleVariable<CSSColorValue>()
    val OnPrimaryContainer by StyleVariable<CSSColorValue>()
    val Secondary by StyleVariable<CSSColorValue>()
    val OnSecondary by StyleVariable<CSSColorValue>()
    val SecondaryContainer by StyleVariable<CSSColorValue>()
    val OnSecondaryContainer by StyleVariable<CSSColorValue>()
    val Tertiary by StyleVariable<CSSColorValue>()
    val OnTertiary by StyleVariable<CSSColorValue>()
    val TertiaryContainer by StyleVariable<CSSColorValue>()
    val OnTertiaryContainer by StyleVariable<CSSColorValue>()
    val Error by StyleVariable<CSSColorValue>()
    val OnError by StyleVariable<CSSColorValue>()
    val ErrorContainer by StyleVariable<CSSColorValue>()
    val OnErrorContainer by StyleVariable<CSSColorValue>()
    val Background by StyleVariable<CSSColorValue>()
    val OnBackground by StyleVariable<CSSColorValue>()
    val Surface by StyleVariable<CSSColorValue>()
    val OnSurface by StyleVariable<CSSColorValue>()
    val SurfaceVariant by StyleVariable<CSSColorValue>()
    val OnSurfaceVariant by StyleVariable<CSSColorValue>()
    val Outline by StyleVariable<CSSColorValue>()
    val OutlineVariant by StyleVariable<CSSColorValue>()
    val Scrim by StyleVariable<CSSColorValue>()
    val InverseSurface by StyleVariable<CSSColorValue>()
    val InverseOnSurface by StyleVariable<CSSColorValue>()
    val InversePrimary by StyleVariable<CSSColorValue>()
    val SurfaceDim by StyleVariable<CSSColorValue>()
    val SurfaceBright by StyleVariable<CSSColorValue>()
    val SurfaceContainerLowest by StyleVariable<CSSColorValue>()
    val SurfaceContainerLow by StyleVariable<CSSColorValue>()
    val SurfaceContainer by StyleVariable<CSSColorValue>()
    val SurfaceContainerHigh by StyleVariable<CSSColorValue>()
    val SurfaceContainerHighest by StyleVariable<CSSColorValue>()
}

@InitSilk
fun initColorScheme(ctx: InitSilkContext) {
    ctx.stylesheet.registerStyleBase(":root, [data-theme=\"light\"]") {
        Modifier
            .setVariable(ColorScheme.Primary, Color.argb(0xFF306A42))
            .setVariable(ColorScheme.OnPrimary, Color.argb(0xFFFFFFFF))
            .setVariable(ColorScheme.PrimaryContainer, Color.argb(0xFFB3F1BF))
            .setVariable(ColorScheme.OnPrimaryContainer, Color.argb(0xFF16512C))
            .setVariable(ColorScheme.Secondary, Color.argb(0xFF8E4D2D))
            .setVariable(ColorScheme.OnSecondary, Color.argb(0xFFFFFFFF))
            .setVariable(ColorScheme.SecondaryContainer, Color.argb(0xFFFFDBCC))
            .setVariable(ColorScheme.OnSecondaryContainer, Color.argb(0xFF713718))
            .setVariable(ColorScheme.Tertiary, Color.argb(0xFF536525))
            .setVariable(ColorScheme.OnTertiary, Color.argb(0xFFFFFFFF))
            .setVariable(ColorScheme.TertiaryContainer, Color.argb(0xFFD5EC9D))
            .setVariable(ColorScheme.OnTertiaryContainer, Color.argb(0xFF3B4D0F))
            .setVariable(ColorScheme.Error, Color.argb(0xFFBA1A1A))
            .setVariable(ColorScheme.OnError, Color.argb(0xFFFFFFFF))
            .setVariable(ColorScheme.ErrorContainer, Color.argb(0xFFFFDAD6))
            .setVariable(ColorScheme.OnErrorContainer, Color.argb(0xFF93000A))
            .setVariable(ColorScheme.Background, Color.argb(0xFFF6FBF3))
            .setVariable(ColorScheme.OnBackground, Color.argb(0xFF181D18))
            .setVariable(ColorScheme.Surface, Color.argb(0xFFFCFAED))
            .setVariable(ColorScheme.OnSurface, Color.argb(0xFF1B1C14))
            .setVariable(ColorScheme.SurfaceVariant, Color.argb(0xFFDCE5DD))
            .setVariable(ColorScheme.OnSurfaceVariant, Color.argb(0xFF404943))
            .setVariable(ColorScheme.Outline, Color.argb(0xFF707973))
            .setVariable(ColorScheme.OutlineVariant, Color.argb(0xFFC0C9C1))
            .setVariable(ColorScheme.Scrim, Color.argb(0xFF000000))
            .setVariable(ColorScheme.InverseSurface, Color.argb(0xFF303128))
            .setVariable(ColorScheme.InverseOnSurface, Color.argb(0xFFF3F1E4))
            .setVariable(ColorScheme.InversePrimary, Color.argb(0xFF98D5A4))
            .setVariable(ColorScheme.SurfaceDim, Color.argb(0xFFDCDACE))
            .setVariable(ColorScheme.SurfaceBright, Color.argb(0xFFFCFAED))
            .setVariable(ColorScheme.SurfaceContainerLowest, Color.argb(0xFFFFFFFF))
            .setVariable(ColorScheme.SurfaceContainerLow, Color.argb(0xFFF6F4E7))
            .setVariable(ColorScheme.SurfaceContainer, Color.argb(0xFFF0EEE1))
            .setVariable(ColorScheme.SurfaceContainerHigh, Color.argb(0xFFEAE9DC))
            .setVariable(ColorScheme.SurfaceContainerHighest, Color.argb(0xFFE5E3D6))
    }

    ctx.stylesheet.registerStyleBase("[data-theme=\"dark\"]") {
        Modifier
            .setVariable(ColorScheme.Primary, Color.argb(0xFF98D5A4))
            .setVariable(ColorScheme.OnPrimary, Color.argb(0xFF00391A))
            .setVariable(ColorScheme.PrimaryContainer, Color.argb(0xFF16512C))
            .setVariable(ColorScheme.OnPrimaryContainer, Color.argb(0xFFB3F1BF))
            .setVariable(ColorScheme.Secondary, Color.argb(0xFFFFB694))
            .setVariable(ColorScheme.OnSecondary, Color.argb(0xFF542104))
            .setVariable(ColorScheme.SecondaryContainer, Color.argb(0xFF713718))
            .setVariable(ColorScheme.OnSecondaryContainer, Color.argb(0xFFFFDBCC))
            .setVariable(ColorScheme.Tertiary, Color.argb(0xFFB9CF83))
            .setVariable(ColorScheme.OnTertiary, Color.argb(0xFF273500))
            .setVariable(ColorScheme.TertiaryContainer, Color.argb(0xFF3B4D0F))
            .setVariable(ColorScheme.OnTertiaryContainer, Color.argb(0xFFD5EC9D))
            .setVariable(ColorScheme.Error, Color.argb(0xFFFFB4AB))
            .setVariable(ColorScheme.OnError, Color.argb(0xFF690005))
            .setVariable(ColorScheme.ErrorContainer, Color.argb(0xFF93000A))
            .setVariable(ColorScheme.OnErrorContainer, Color.argb(0xFFFFDAD6))
            .setVariable(ColorScheme.Background, Color.argb(0xFF101510))
            .setVariable(ColorScheme.OnBackground, Color.argb(0xFFDFE4DC))
            .setVariable(ColorScheme.Surface, Color.argb(0xFF13140D))
            .setVariable(ColorScheme.OnSurface, Color.argb(0xFFE5E3D6))
            .setVariable(ColorScheme.SurfaceVariant, Color.argb(0xFF404943))
            .setVariable(ColorScheme.OnSurfaceVariant, Color.argb(0xFFC0C9C1))
            .setVariable(ColorScheme.Outline, Color.argb(0xFF8A938C))
            .setVariable(ColorScheme.OutlineVariant, Color.argb(0xFF404943))
            .setVariable(ColorScheme.Scrim, Color.argb(0xFF000000))
            .setVariable(ColorScheme.InverseSurface, Color.argb(0xFFE5E3D6))
            .setVariable(ColorScheme.InverseOnSurface, Color.argb(0xFF303128))
            .setVariable(ColorScheme.InversePrimary, Color.argb(0xFF306A42))
            .setVariable(ColorScheme.SurfaceDim, Color.argb(0xFF13140D))
            .setVariable(ColorScheme.SurfaceBright, Color.argb(0xFF393A31))
            .setVariable(ColorScheme.SurfaceContainerLowest, Color.argb(0xFF0E0F08))
            .setVariable(ColorScheme.SurfaceContainerLow, Color.argb(0xFF1B1C14))
            .setVariable(ColorScheme.SurfaceContainer, Color.argb(0xFF202018))
            .setVariable(ColorScheme.SurfaceContainerHigh, Color.argb(0xFF2A2B22))
            .setVariable(ColorScheme.SurfaceContainerHighest, Color.argb(0xFF35352D))
    }
}
